name: CI

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      ELECTRON_DISABLE_SANDBOX: 1

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1.2.0
        with:
          node-version: "12.x"
      - run: sudo apt-get install xvfb
      - name: Install, lint and build
        run: |
          npm ci
          npm run lint
          npm run build:ci
      - name: Run tests
        run: xvfb-run --auto-servernum npm run test
      - name: Clean xvfb
        run: |
          xvfb_pids=`ps aux | grep tmp/xvfb-run | grep -v grep | awk '{print $2}'`
          if [ "$xvfb_pids" != "" ]; then
            echo "Killing the following xvfb processes: $xvfb_pids"
            sudo kill $xvfb_pids
          else
            echo "No xvfb processes to kill"
          fi
        env:
          CI: true
